version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: cinmax_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/postgres-init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - cinmax-network

  user-service:
    build: .
    ports:
      - "9090:9090"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      DB_URL: jdbc:postgresql://postgres:5432/cinmax_db
      DB_USER: postgres
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - cinmax-network

volumes:
  postgres_data:

networks:
  cinmax-network:
    driver: bridge